### ISSUE TITLE
Failed to load plugin 'Crossbar'. Reason: LoadLibraryA failed. (Error: 126)

### ISSUE THREAD

**Issue by AliekberFFXI** [ThornyFFXI/Crossbar#10]
I'm getting an error when I try to use this plugin for HorizonXI (Ashita):

```
[Ashita] Failed to load plugin 'Crossbar'. Reason: LoadLibraryA failed. (Error: 126)
[Ashita] Error Message: The specified module could not be found.
```
I checked the logs folder, and it's completely empty. Additionally, I have the following VS redistributables installed:

- MSVC 2005 8.0.61001
- MSVC 2005 (x64) 8.0.61001
- MSVC 2008 (x64) 9.0.30729.6161
- MSVC 2008 (x86) 9.0.21022.218
- MSVC 2008 (x86) 9.0.30729.6161
- MSVC 2010 (x64) 10.0.40219
- MSVC 2010 (x86) 10.0.40219
- MSVC 2012 (x64) 11.0.61030
- MSVC 2012 (x86) 11.0.61030
- MSVC 2013 (x64) 12.0.30501
- MSVC 2013 (x64) 12.0.40664
- MSVC 2013 (x86) 12.0.30501
- MSVC 2013 (x86) 12.0.40664
- MSVC 2015-2022 (x64) 14.34.31938
- MSVC 2015-2022 (x86) 14.34.31938

Any advice?

**Comment by lrwilliams99** [comment]
Also getting this error.

**Comment by ThornyFFXI** [comment]
The most obvious cause would be not having installed to the correct directory.  The crossbar.dll plugin belongs in your ashita/plugins folder.  The zip as a whole should be extracted directly to your ashita folder to fall into the correct location.

**Comment by AliekberFFXI** [comment]
Looks like I had two instances of HorizonXI installed somehow. I put the Crossbar plugin in one but was running the other. Copied it over to the correct instance (and deleted the other one) and now I can load the plugin. Thanks!
