### ISSUE TITLE
Combersome Complex Macros

### ISSUE THREAD

**Issue by Azostar** [ThornyFFXI/Crossbar#11]
Relating to issue #5.

I have used this plugin for a few weeks and it has been a great help in overcoming the dated UI elements of FFXI.

I use the crossbars palette feature often which means some scripts will be re-used in palettes that I can't stick in the Job or Global palette's. 

One feature I would love to see is the ability to access my scripts without having to go through the process of using the '/cbm' command  browsing my scripts folder to recall what the script paths are. 

Is this something you would be willing to consider?

**Comment by ThornyFFXI** [comment]
Crossbar has been replaced with https://github.com/ThornyFFXI/tCrossBar long term.  This version uses an imgui binding interface with full support for multi-line macros built into it, as well as numerous other improvements to appearance and behavior.  I have no plans to further alter Crossbar.  Note that tCrossBar requires you to update to Ashita 4.15.

**Comment by Azostar** [comment]
Great, I'll get on top of that now!
