### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by AliekberFFXI** [ThornyFFXI/Crossbar#12]
When I load the plugin initially, everything works. But when I try to bind something, my game crashes. When I come back after that and try to load the plugin, I get the following:
```
[Ashita] Failed to load plugin 'crossbar'. Reason: Plugin threw an unknown exception.
[Ashita] The internal ParseInputText hook threw an exception.. Exception: EXCEPTION_ACCESS_VIOLATION (C0000005). [Ptr: 001660F3]
```
If I delete the settings.xml and the job binding xml, then the plugin becomes able to load again. This is on v1.22 (for whatever reason, the v1.25 does not load at all for me, it just complains that it's expecting interface 4.14 but is given interface 4.15).

**Comment by ThornyFFXI** [comment]
Ashita interface version defines the API available to plugins and addons.  If you are on Ashita 4.14, you must use Ashita 4.14 plugins so the function calls match up.  This is why you cannot use 1.25, as Horizon is currently on an outdated version of Ashita.

Crossbar has been replaced with tCrossbar, which massively improves the binding interface and seperates the renderer into a plugin so the logic can be handled from an addon.  It also requires 4.15.

If I had an easy answer, I would give you it, but I am not willing to spend very long on an outdated version of a deprecated plugin.  I would recommend either updating to 4.15(this will require you to update your other plugins as well) and getting tCrossbar or waiting until Horizon does it for you.

If I had to guess, the files may not have been properly installed.  Everything in the zip should be placed relative to the main ashita directory, nothing should need to be moved.
