### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by State-Null** [ThornyFFXI/Crossbar#13]
Seeing as how this fork is newer than the original creator...
Is this version also compatible with Windower?

Is it possible for this to be updated to support the new sortie ws and the updated skillchains Lua?

**Comment by ThornyFFXI** [comment]
This is not a fork, it is a unique plugin written with some of the same ideas.  It is only for Ashita, and cannot be made compatible with Windower.  It has also been replaced by:
https://github.com/ThornyFFXI/tCrossbar (which is also not compatible with windower)

Whatever skillchains.lua you are talking about is almost certainly not compatible with it, though I will certainly update tCrossBar to include sortie WS in the near future.
