### ISSUE TITLE
Sub job limited selection

### ISSUE THREAD

**Issue by KoikazeJunsei** [ThornyFFXI/Crossbar#4]
Noticed that sub job is limited to 45. I would like to request maybe a toggle or cmd that could uncap that to 99.

**Comment by ThornyFFXI** [comment]
If you set 'UseLevelSync' to true in the configuration file, Crossbar will populate possible actions based on the actual level your client reports your sub as, rather than the limit posed by your main job.  This should allow you to do what you're trying to do.
