### ISSUE TITLE
Complex / Multi-Stage Macros

### ISSUE THREAD

**Issue by nickandwolf** [ThornyFFXI/Crossbar#5]
Hello, could you please put a little tutorial on how to do multi-stage macros?

`/targetnpc`
`/ja "Provoke" <t>`
`/p Pulling <t>!`

**Comment by ThornyFFXI** [comment]
Set the macro to a custom string that executes a script:
`/exec targetprovoke`

Go into ashita folder/scripts and create `targetprovoke.txt`.

Fill in the script with:
```
/targetnpc
/ja "Provoke" <t>
/p Pulling <t>!
```

If you want to avoid clutter you can also use a subfolder, such as scripts/crossbar/targetprovoke.txt and change the macro to `/exec crossbar/targetprovoke`.

**Comment by nickandwolf** [comment]
That's awesome, thank you! Is there a way to include autotranslate in the .txt file?
