### ISSUE TITLE
Unable to resize the crossbar

### ISSUE THREAD

**Issue by Rynzer** [ThornyFFXI/Crossbar#7]
Hello, there does not seem to be any way to resize the crossbar UI. This makes the crossbar nearly impossible to see and read on larger screens. The font for the spell names is also quite tiny and not able to be enlarged.

**Comment by ThornyFFXI** [comment]
The theme XMLs (resources/crossbar/themes/) can be used to resize everything, however the long term goal is to replace crossbar with an addon so further customization will not be added to the plugin.
