### ISSUE TITLE
Can't change icons

### ISSUE THREAD

**Issue by Citrus333** [ThornyFFXI/Crossbar#8]
Trying to change the icons of some abilities, mostly basic ones like /fish or /attack that just use the default command icon.  However when setting the binding using the change icon in the GUI it doesn't seem to have any effect.  '/cbm fish' doesn't work or '/cbm fish.png' but if I just rename the image I want to default.png then it works but changes the default for all images.

Is there some way to do this properly?

**Comment by ThornyFFXI** [comment]
Path should be relative to ashita/resources/crossbar.

For example, store your file in:
`Ashita/resources/crossbar/custom/Fish.png`
(on horizon, this would be `HorizonXI/Game/resources/crossbar/custom/Fish.png`)

And set your custom image to:
`custom/Fish.png`
