### ISSUE TITLE
Failed to load theme

### ISSUE THREAD

**Issue by Andrewthedev** [ThornyFFXI/Crossbar#9]
Ashita (version) - 4.0.0.6

Crossbar  (version) - 4.14

I can't seem to get this working. I downloaded the plugin and added the DLL to the plugins folder. When I load the plugin it loads but gives an error saying it can not load the theme. I looked to verify the theme file was generated and it was. So, I'm unsure what to do to get it working. 

I am a long-time windower user and looking to change to Ashita.

**Comment by ThornyFFXI** [comment]
The issue tracker is for problems with the plugin, not difficulties setting it up.  The release folder includes a 'resources' directory that should also be copied to your base Ashita folder, which is most likely the cause of your problems if you only moved the plugin DLL itself.  If you'd like more assistance, you should join the Ashita discord.

**Comment by Andrewthedev** [comment]
Thank you, Thorny!
